name: Java CI with Maven on Local runner

on: [push]

jobs:
  do-the-magic:
    runs-on: java-17
    steps:
    - uses: actions/checkout@v4
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
